Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Sub "10.87.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: bungee-app
          Value: !Join ['-',['bungee', '${env:APP_NAME}']]
        - Key: bungee-name
          Value: !Join ['-',['bungee', '${env:APP_NAME}','vpc']]

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: bungee-app
          Value: !Join ['-',['bungee', '${env:APP_NAME}']]
        - Key: bungee-name
          Value: !Join ['-',['bungee', '${env:APP_NAME}','internet-gateway']]

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Sub "10.70.10.0/24"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: bungee-app
          Value: !Join ['-',['bungee', '${env:APP_NAME}']]
        - Key: bungee-name
          Value: !Join ['-',['bungee', '${env:APP_NAME}','public-subnet-a']]
  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Sub "10.70.11.0/24"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: bungee-app
          Value: !Join ['-',['bungee', '${env:APP_NAME}']]
        - Key: bungee-name
          Value: !Join ['-',['bungee', '${env:APP_NAME}','public-subnet-b']]

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: bungee-app
          Value: !Join ['-',['bungee', '${env:APP_NAME}']]
        - Key: bungee-name
          Value: !Join ['-',['bungee', '${env:APP_NAME}','public-route-table']]

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      Tags:
        - Key: bungee-app
          Value: !Join ['-',['bungee', '${env:APP_NAME}']]
        - Key: bungee-name
          Value: !Join ['-',['bungee', '${env:APP_NAME}','default-public-route']]

  PublicSubnetRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnetA
      Tags:
        - Key: bungee-app
          Value: !Join ['-',['bungee', '${env:APP_NAME}']]
        - Key: bungee-name
          Value: !Join ['-',['bungee', '${env:APP_NAME}','public-subnet-route-table-association-a']]
  PublicSubnetRouteTableAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnetB
      Tags:
        - Key: bungee-app
          Value: !Join ['-',['bungee', '${env:APP_NAME}']]
        - Key: bungee-name
          Value: !Join ['-',['bungee', '${env:APP_NAME}','public-subnet-route-table-association-b']]
